# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cholitos_law', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('hurt', models.BooleanField()),
                ('comment', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=200)),
                ('rescue', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 27, 3, 27, 44, 58994, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(default='hembra', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
