# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cholitos_law', '0002_auto_20170927_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birth',
            field=models.DateTimeField(),
        ),
    ]
