# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cholitos_law', '0004_animal_animal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('municipality', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cholitos_law.Municipality')),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default='PERRO', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='ong',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cholitos_law.Ong'),
        ),
    ]
