# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cholitos_law', '0005_auto_20171023_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='animals_options',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default='Perro', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='municipality',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cholitos_law.Municipality'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='type_complaint',
            field=models.CharField(choices=[('Abandono de Calle', 'Abandono de Calle'), ('Exposición a temperaturas extremas', 'Exposición a temperaturas extremas'), ('Falta de Agua', 'Falta de Agua'), ('Falta de Comida', 'Falta de Comida'), ('Violencia', 'Violencia'), ('Venta ambulante', 'Venta ambulante')], default='Abandono de Calle', max_length=30),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default='Perro', max_length=100),
        ),
    ]
