# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cholitos_law', '0007_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'permissions': (('is_muni', 'Can view Munis'),)},
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
